#!/usr/bin/env python

import sys
import time
import json
import re
from os import environ, path


def get_color(colorstr):
    colors = {
        'black': 0,
        'red': 1,
        'green': 2,
        'yellow': 3,
        'blue': 4,
        'magenta': 5,
        'cyan': 6,
        'white': 7
    }
    return colors[colorstr]


def wrap_with_color(line, color):
    color_code = get_color(color)
    fmt_begin = '\x1b[3%sm' % color_code
    fmt_end = '\x1b[0m'
    return fmt_begin + line + fmt_end


def main():
    try:
        color_file = environ.get('COLORTAIL_FILE', '~/.colortailrc')
        color_file_handle = open(path.expanduser(color_file))
        color_file_json = json.load(color_file_handle)
        profile = color_file_json[sys.argv[1]]
        last_line = ''
        while True:
            line = sys.stdin.readline()
            if line == '':
                sys.exit(0)
            if line != last_line:
                written = False
                for key, value in profile.iteritems():
                    if re.findall(key, line):
                        sys.stdout.write(wrap_with_color(line, value))
                        written = True
                last_line = line
                if not written:
                    sys.stdout.write(line)
            time.sleep(0.01)
    except KeyError:
        sys.stdout.write('profile not found')
        sys.exit(-1)


if __name__ == '__main__':
    main()
    sys.exit(0)
